spring:
  datasource:
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/jjlwnqjd
    username: jjlwnqjd
    password: vSLE4W7Vtr6Dp0avX-cen5VFo6Mijz07
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC + 1

